/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author morales
 */
public class Menu extends javax.swing.JFrame {

    public static boolean qrframestate=false;
    
    public Menu() {
        initComponents();
        this.setTitle("SiBi");
      //  setExtendedState(MAXIMIZED_BOTH);
//        panel_menu_aux.setVisible(false);
//        panel_menu_qr.setVisible(false);
       
        this.setIconImage(new ImageIcon(getClass().getResource("/IMG/logobeta1.png")).getImage());
        String fecha = new SimpleDateFormat("EEEE dd '-' MMMM '-' YYYY").format(new Date());
        lbl_mfecha.setText(fecha);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_superior_menu = new javax.swing.JPanel();
        lbl_menu_nombre = new javax.swing.JLabel();
        panel_manu_foto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_menu_cerrarsesion = new javax.swing.JLabel();
        panel_manu_foto2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_mfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();
        panel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_menu_inferior2 = new javax.swing.JPanel();
        panel_menu_libros2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel_menu_estudiantes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel_menu_prestamos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panel_menu_reportes2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_superior_menu.setBackground(new java.awt.Color(255, 255, 255));
        panel_superior_menu.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        panel_superior_menu.setPreferredSize(new java.awt.Dimension(1000, 120));

        lbl_menu_nombre.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lbl_menu_nombre.setText("Usuario");

        panel_manu_foto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/infographic-element-1_icon-icons.com_58018.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_manu_fotoLayout = new javax.swing.GroupLayout(panel_manu_foto);
        panel_manu_foto.setLayout(panel_manu_fotoLayout);
        panel_manu_fotoLayout.setHorizontalGroup(
            panel_manu_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_manu_fotoLayout.setVerticalGroup(
            panel_manu_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lbl_menu_cerrarsesion.setForeground(new java.awt.Color(51, 102, 255));
        lbl_menu_cerrarsesion.setText("cerrar sesion");
        lbl_menu_cerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_menu_cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menu_cerrarsesionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_menu_cerrarsesionMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_menu_cerrarsesionMouseEntered(evt);
            }
        });

        panel_manu_foto2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/grafica.png"))); // NOI18N

        lbl_mfecha.setForeground(new java.awt.Color(102, 102, 102));
        lbl_mfecha.setText("00-00-00");

        jLabel3.setText("Sistema bibliotecario");

        javax.swing.GroupLayout panel_manu_foto2Layout = new javax.swing.GroupLayout(panel_manu_foto2);
        panel_manu_foto2.setLayout(panel_manu_foto2Layout);
        panel_manu_foto2Layout.setHorizontalGroup(
            panel_manu_foto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_manu_foto2Layout.createSequentialGroup()
                .addGroup(panel_manu_foto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_mfecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );
        panel_manu_foto2Layout.setVerticalGroup(
            panel_manu_foto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_manu_foto2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_mfecha)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout panel_superior_menuLayout = new javax.swing.GroupLayout(panel_superior_menu);
        panel_superior_menu.setLayout(panel_superior_menuLayout);
        panel_superior_menuLayout.setHorizontalGroup(
            panel_superior_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_superior_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_manu_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_superior_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_menu_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_menu_cerrarsesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                .addComponent(panel_manu_foto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        panel_superior_menuLayout.setVerticalGroup(
            panel_superior_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_superior_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_superior_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_superior_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_superior_menuLayout.createSequentialGroup()
                            .addComponent(lbl_menu_nombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_menu_cerrarsesion)
                            .addGap(20, 20, 20))
                        .addComponent(panel_manu_foto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_manu_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_superior_menu, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panel1.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(panel1, java.awt.BorderLayout.PAGE_START);

        panel2.setBackground(new java.awt.Color(245, 245, 245));
        panel2.setPreferredSize(new java.awt.Dimension(20, 536));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jPanel1.add(panel2, java.awt.BorderLayout.LINE_START);

        panel3.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(panel3, java.awt.BorderLayout.PAGE_END);

        panel5.setBackground(new java.awt.Color(245, 245, 245));
        panel5.setPreferredSize(new java.awt.Dimension(20, 536));

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jPanel1.add(panel5, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setBackground(new java.awt.Color(245, 245, 245));
        jScrollPane1.setBorder(null);

        panel_menu_inferior2.setBackground(new java.awt.Color(245, 245, 245));
        panel_menu_inferior2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_menu_inferior2.setLayout(new java.awt.GridLayout(2, 4, 20, 20));

        panel_menu_libros2.setBackground(new java.awt.Color(245, 245, 245));
        panel_menu_libros2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_menu_libros2.setPreferredSize(new java.awt.Dimension(200, 220));
        panel_menu_libros2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_menu_libros2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_menu_libros2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_menu_libros2MouseEntered(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(239, 200, 74));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><h3>Libros</html></h3>");
        jLabel8.setOpaque(true);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/book.png"))); // NOI18N

        javax.swing.GroupLayout panel_menu_libros2Layout = new javax.swing.GroupLayout(panel_menu_libros2);
        panel_menu_libros2.setLayout(panel_menu_libros2Layout);
        panel_menu_libros2Layout.setHorizontalGroup(
            panel_menu_libros2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
            .addGroup(panel_menu_libros2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_menu_libros2Layout.setVerticalGroup(
            panel_menu_libros2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_libros2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_menu_inferior2.add(panel_menu_libros2);

        panel_menu_estudiantes.setBackground(new java.awt.Color(255, 255, 255));
        panel_menu_estudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_menu_estudiantes.setPreferredSize(new java.awt.Dimension(200, 220));
        panel_menu_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_menu_estudiantesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_menu_estudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_menu_estudiantesMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(69, 179, 156));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html><h3>Clientes</html></h3>");
        jLabel10.setOpaque(true);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/student.png"))); // NOI18N

        javax.swing.GroupLayout panel_menu_estudiantesLayout = new javax.swing.GroupLayout(panel_menu_estudiantes);
        panel_menu_estudiantes.setLayout(panel_menu_estudiantesLayout);
        panel_menu_estudiantesLayout.setHorizontalGroup(
            panel_menu_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
            .addGroup(panel_menu_estudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_menu_estudiantesLayout.setVerticalGroup(
            panel_menu_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_estudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_menu_inferior2.add(panel_menu_estudiantes);

        panel_menu_prestamos.setBackground(new java.awt.Color(255, 255, 255));
        panel_menu_prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_menu_prestamos.setPreferredSize(new java.awt.Dimension(200, 220));
        panel_menu_prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_menu_prestamosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_menu_prestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_menu_prestamosMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(104, 97, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<html><h3>Prestamos</html></h3>");
        jLabel12.setOpaque(true);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/layout.png"))); // NOI18N

        javax.swing.GroupLayout panel_menu_prestamosLayout = new javax.swing.GroupLayout(panel_menu_prestamos);
        panel_menu_prestamos.setLayout(panel_menu_prestamosLayout);
        panel_menu_prestamosLayout.setHorizontalGroup(
            panel_menu_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
            .addGroup(panel_menu_prestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_menu_prestamosLayout.setVerticalGroup(
            panel_menu_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_prestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_menu_inferior2.add(panel_menu_prestamos);

        panel_menu_reportes2.setBackground(new java.awt.Color(255, 255, 255));
        panel_menu_reportes2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_menu_reportes2.setPreferredSize(new java.awt.Dimension(200, 220));
        panel_menu_reportes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_menu_reportes2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_menu_reportes2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_menu_reportes2MouseEntered(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(201, 84, 66));
        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("<html><h3>Reportes</html></h3>");
        jLabel20.setOpaque(true);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/trabajo-en-equipo.png"))); // NOI18N

        javax.swing.GroupLayout panel_menu_reportes2Layout = new javax.swing.GroupLayout(panel_menu_reportes2);
        panel_menu_reportes2.setLayout(panel_menu_reportes2Layout);
        panel_menu_reportes2Layout.setHorizontalGroup(
            panel_menu_reportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20)
            .addGroup(panel_menu_reportes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_menu_reportes2Layout.setVerticalGroup(
            panel_menu_reportes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_reportes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_menu_inferior2.add(panel_menu_reportes2);

        jScrollPane1.setViewportView(panel_menu_inferior2);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1010, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_menu_libros2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_libros2MouseEntered
      panel_menu_libros2.setBackground(new Color(241,241,241));
    }//GEN-LAST:event_panel_menu_libros2MouseEntered

    private void panel_menu_libros2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_libros2MouseExited
      panel_menu_libros2.setBackground(new Color(255,255,255));
    
    }//GEN-LAST:event_panel_menu_libros2MouseExited

    private void panel_menu_estudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_estudiantesMouseEntered
       panel_menu_estudiantes.setBackground(new Color(241,241,241));
    
    }//GEN-LAST:event_panel_menu_estudiantesMouseEntered

    private void panel_menu_estudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_estudiantesMouseExited
panel_menu_estudiantes.setBackground(new Color(255,255,255));
        }//GEN-LAST:event_panel_menu_estudiantesMouseExited

    private void panel_menu_prestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_prestamosMouseEntered
  panel_menu_prestamos.setBackground(new Color(241,241,241));
        }//GEN-LAST:event_panel_menu_prestamosMouseEntered

    private void panel_menu_prestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_prestamosMouseExited
  panel_menu_prestamos.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_panel_menu_prestamosMouseExited

    private void lbl_menu_cerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menu_cerrarsesionMouseClicked
        Ingreso in = new Ingreso();
        int dialogResult = JOptionPane.showConfirmDialog (null, "¿Seguro de que quieres cerrar sesion?");
        if(dialogResult == JOptionPane.YES_OPTION){
        in.setVisible(true);
        dispose();
         }else{
            
        }
        
    }//GEN-LAST:event_lbl_menu_cerrarsesionMouseClicked

    private void panel_menu_libros2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_libros2MouseClicked
        Libros l = new Libros();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_panel_menu_libros2MouseClicked

    private void panel_menu_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_estudiantesMouseClicked
        Estudiantes est = new Estudiantes();
        est.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_panel_menu_estudiantesMouseClicked

    private void lbl_menu_cerrarsesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menu_cerrarsesionMouseEntered
       //ST
       Font font = lbl_menu_cerrarsesion.getFont();
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE,TextAttribute.UNDERLINE_ON);
       lbl_menu_cerrarsesion.setFont(font.deriveFont(attributes));
       
    }//GEN-LAST:event_lbl_menu_cerrarsesionMouseEntered

    private void lbl_menu_cerrarsesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menu_cerrarsesionMouseExited
        // QS
       Font font = lbl_menu_cerrarsesion.getFont();
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE,-1);
       lbl_menu_cerrarsesion.setFont(font.deriveFont(attributes));
         
    }//GEN-LAST:event_lbl_menu_cerrarsesionMouseExited

    private void panel_menu_prestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_prestamosMouseClicked
       Menu_prestamos pm = new Menu_prestamos();
       pm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_panel_menu_prestamosMouseClicked

    private void panel_menu_reportes2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_reportes2MouseClicked
        Reportes r = new Reportes();
        r.setVisible(true);
    }//GEN-LAST:event_panel_menu_reportes2MouseClicked

    private void panel_menu_reportes2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_reportes2MouseExited
        panel_menu_reportes2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_panel_menu_reportes2MouseExited

    private void panel_menu_reportes2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_menu_reportes2MouseEntered
        panel_menu_reportes2.setBackground(new Color(241,241,241));
    }//GEN-LAST:event_panel_menu_reportes2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_menu_cerrarsesion;
    public static javax.swing.JLabel lbl_menu_nombre;
    private javax.swing.JLabel lbl_mfecha;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel_manu_foto;
    private javax.swing.JPanel panel_manu_foto2;
    private javax.swing.JPanel panel_menu_estudiantes;
    private javax.swing.JPanel panel_menu_inferior2;
    private javax.swing.JPanel panel_menu_libros2;
    private javax.swing.JPanel panel_menu_prestamos;
    private javax.swing.JPanel panel_menu_reportes;
    private javax.swing.JPanel panel_menu_reportes1;
    private javax.swing.JPanel panel_menu_reportes2;
    private javax.swing.JPanel panel_superior_menu;
    // End of variables declaration//GEN-END:variables
}
