
package UI;

import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mmorales
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public static boolean CheckLibro= false;
    public static boolean CheckEstudiantes= false;
    public static boolean CheckPrestamo= false;
    public static boolean CheckPersonal= false;
    
    
    public Reportes() {
        initComponents();
        setTitle("SiBi");
        CheckLibro=false; 
        CheckEstudiantes=false; 
        CheckPrestamo=false; 
        CheckPersonal=false; 
        Rwait.setLocationRelativeTo(null);
        Rready.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rwait = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblwaitr = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Rready = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblready = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Radver = new javax.swing.JDialog();
        paneladver = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblwaitr1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        lbl_encabezado_qr = new javax.swing.JLabel();
        lbl_cerrar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Panel_centroreportes = new javax.swing.JPanel();
        Center_encabezado = new javax.swing.JPanel();
        panel_button = new javax.swing.JPanel();
        Optionreport = new javax.swing.JPanel();
        RLibro = new javax.swing.JPanel();
        lblRLibro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Restudiantes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblREstudiantes = new javax.swing.JLabel();
        RPrestamos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblRPrestamos = new javax.swing.JLabel();
        RPersonal = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblRPersonal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_BotonesRep = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btn_generarreportes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        Rwait.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Rwait.setMinimumSize(new java.awt.Dimension(400, 128));
        Rwait.setUndecorated(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/relojch.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 64));
        jPanel9.add(jLabel8, java.awt.BorderLayout.LINE_START);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        lblwaitr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblwaitr.setText("<html><h2>Generando reporte...</h2></html>");

        jLabel12.setText("Espere un momento");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblwaitr, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblwaitr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        Rwait.getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        Rready.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Rready.setTitle("Mensaje");
        Rready.setAlwaysOnTop(true);
        Rready.setMinimumSize(new java.awt.Dimension(370, 140));
        Rready.setResizable(false);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/garrapata.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 64));
        jPanel13.add(jLabel10, java.awt.BorderLayout.LINE_START);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        lblready.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblready.setText("<html><h2>Listo</h2></html>");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblready, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblready, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel13.add(jPanel14, java.awt.BorderLayout.CENTER);

        Rready.getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        Radver.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Radver.setTitle("Mensaje");
        Radver.setAlwaysOnTop(true);
        Radver.setMinimumSize(new java.awt.Dimension(400, 140));
        Radver.setResizable(false);

        paneladver.setBackground(new java.awt.Color(255, 255, 255));
        paneladver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paneladver.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/alerta.png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(80, 64));
        paneladver.add(jLabel17, java.awt.BorderLayout.LINE_START);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        lblwaitr1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblwaitr1.setText("<html><h3>Testing...</h3></html>");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblwaitr1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblwaitr1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneladver.add(jPanel16, java.awt.BorderLayout.CENTER);

        Radver.getContentPane().add(paneladver, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SiBi");

        header.setBackground(new java.awt.Color(0, 102, 255));
        header.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        header.setLayout(new java.awt.BorderLayout());

        lbl_encabezado_qr.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_encabezado_qr.setForeground(new java.awt.Color(254, 254, 254));
        lbl_encabezado_qr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_encabezado_qr.setText("<html><h1>Reportes</h1>");
        lbl_encabezado_qr.setPreferredSize(new java.awt.Dimension(200, 50));
        lbl_encabezado_qr.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        header.add(lbl_encabezado_qr, java.awt.BorderLayout.CENTER);

        lbl_cerrar.setBackground(new java.awt.Color(0, 0, 0));
        lbl_cerrar.setFont(new java.awt.Font("Gargi-1.2b", 1, 12)); // NOI18N
        lbl_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/baseline_keyboard_backspace_white_18dp.png"))); // NOI18N
        lbl_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseClicked(evt);
            }
        });
        header.add(lbl_cerrar, java.awt.BorderLayout.LINE_START);

        jLabel7.setMaximumSize(new java.awt.Dimension(36, 36));
        jLabel7.setMinimumSize(new java.awt.Dimension(36, 36));
        jLabel7.setPreferredSize(new java.awt.Dimension(36, 36));
        header.add(jLabel7, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Panel_centroreportes.setBackground(new java.awt.Color(255, 255, 255));
        Panel_centroreportes.setLayout(new java.awt.BorderLayout());

        Center_encabezado.setBackground(new java.awt.Color(245, 245, 245));
        Center_encabezado.setPreferredSize(new java.awt.Dimension(589, 20));
        Center_encabezado.setLayout(new java.awt.BorderLayout());
        Panel_centroreportes.add(Center_encabezado, java.awt.BorderLayout.PAGE_START);

        panel_button.setBackground(new java.awt.Color(245, 245, 245));
        panel_button.setPreferredSize(new java.awt.Dimension(589, 20));
        panel_button.setLayout(new java.awt.GridLayout(1, 0));
        Panel_centroreportes.add(panel_button, java.awt.BorderLayout.PAGE_END);

        Optionreport.setBackground(new java.awt.Color(245, 245, 245));
        Optionreport.setLayout(new java.awt.GridLayout(1, 3, 20, 20));

        RLibro.setBackground(new java.awt.Color(255, 255, 255));
        RLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RLibroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RLibroMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RLibroMouseEntered(evt);
            }
        });

        lblRLibro.setBackground(new java.awt.Color(239, 200, 74));
        lblRLibro.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblRLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblRLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRLibro.setText("<html><h3>Libros</html></h3>");
        lblRLibro.setOpaque(true);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/book.png"))); // NOI18N

        javax.swing.GroupLayout RLibroLayout = new javax.swing.GroupLayout(RLibro);
        RLibro.setLayout(RLibroLayout);
        RLibroLayout.setHorizontalGroup(
            RLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRLibro)
            .addGroup(RLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        RLibroLayout.setVerticalGroup(
            RLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Optionreport.add(RLibro);

        Restudiantes.setBackground(new java.awt.Color(255, 255, 255));
        Restudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Restudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestudiantesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestudiantesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestudiantesMouseEntered(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/student.png"))); // NOI18N

        lblREstudiantes.setBackground(new java.awt.Color(69, 179, 156));
        lblREstudiantes.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblREstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        lblREstudiantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblREstudiantes.setText("<html><h3>Clientes</html></h3>");
        lblREstudiantes.setOpaque(true);

        javax.swing.GroupLayout RestudiantesLayout = new javax.swing.GroupLayout(Restudiantes);
        Restudiantes.setLayout(RestudiantesLayout);
        RestudiantesLayout.setHorizontalGroup(
            RestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblREstudiantes)
            .addGroup(RestudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        RestudiantesLayout.setVerticalGroup(
            RestudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RestudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblREstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Optionreport.add(Restudiantes);

        RPrestamos.setBackground(new java.awt.Color(255, 255, 255));
        RPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RPrestamosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RPrestamosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RPrestamosMouseEntered(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/layout.png"))); // NOI18N

        lblRPrestamos.setBackground(new java.awt.Color(104, 97, 255));
        lblRPrestamos.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblRPrestamos.setForeground(new java.awt.Color(255, 255, 255));
        lblRPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRPrestamos.setText("<html><h3>Prestamos</html></h3>");
        lblRPrestamos.setOpaque(true);

        javax.swing.GroupLayout RPrestamosLayout = new javax.swing.GroupLayout(RPrestamos);
        RPrestamos.setLayout(RPrestamosLayout);
        RPrestamosLayout.setHorizontalGroup(
            RPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRPrestamos)
            .addGroup(RPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        RPrestamosLayout.setVerticalGroup(
            RPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPrestamosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Optionreport.add(RPrestamos);

        RPersonal.setBackground(new java.awt.Color(255, 255, 255));
        RPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RPersonalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RPersonalMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RPersonalMouseEntered(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_menu/trabajo-en-equipo.png"))); // NOI18N

        lblRPersonal.setBackground(new java.awt.Color(224, 91, 73));
        lblRPersonal.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblRPersonal.setForeground(new java.awt.Color(255, 255, 255));
        lblRPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRPersonal.setText("<html><h3>Usuarios</html></h3>");
        lblRPersonal.setOpaque(true);

        javax.swing.GroupLayout RPersonalLayout = new javax.swing.GroupLayout(RPersonal);
        RPersonal.setLayout(RPersonalLayout);
        RPersonalLayout.setHorizontalGroup(
            RPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRPersonal)
            .addGroup(RPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        RPersonalLayout.setVerticalGroup(
            RPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Optionreport.add(RPersonal);

        Panel_centroreportes.add(Optionreport, java.awt.BorderLayout.CENTER);

        jPanel1.add(Panel_centroreportes, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));
        jPanel5.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(550, 30));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecciona un reporte para generar (se permite la seleccion multiple)");
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        Panel_BotonesRep.setBackground(new java.awt.Color(255, 255, 255));
        Panel_BotonesRep.setMinimumSize(new java.awt.Dimension(282, 30));
        Panel_BotonesRep.setPreferredSize(new java.awt.Dimension(550, 35));
        Panel_BotonesRep.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(733, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Panel_BotonesRep.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Panel_BotonesRep.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(20, 30));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Panel_BotonesRep.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        btn_generarreportes.setBackground(new java.awt.Color(0, 102, 255));
        btn_generarreportes.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btn_generarreportes.setForeground(new java.awt.Color(255, 255, 255));
        btn_generarreportes.setText("Generar reporte(s)");
        btn_generarreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generarreportes.setFocusable(false);
        btn_generarreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarreportesActionPerformed(evt);
            }
        });
        jPanel12.add(btn_generarreportes);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2);

        Panel_BotonesRep.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel1.add(Panel_BotonesRep, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(799, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_cerrarMouseClicked

    private void RLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLibroMouseEntered
    
     if(CheckLibro == false){
    RLibro.setBackground(new Color(241,241,241));
      }
     else if(CheckLibro == true){
    
     }
    }//GEN-LAST:event_RLibroMouseEntered

    private void RestudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestudiantesMouseEntered
    if(CheckEstudiantes == false){
    Restudiantes.setBackground(new Color(241,241,241));
      }
     else if(CheckEstudiantes == true){
    
     }
    }//GEN-LAST:event_RestudiantesMouseEntered

    private void RPrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPrestamosMouseEntered
    if(CheckPrestamo == false){
    RPrestamos.setBackground(new Color(241,241,241));
      }
     else if(CheckPrestamo == true){
    
     }
    }//GEN-LAST:event_RPrestamosMouseEntered

    private void RLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLibroMouseExited
     if(CheckLibro == false){
    RLibro.setBackground(new Color(255,255,255));
      }
     else if(CheckLibro == true){
    //libro
     }
    
    }//GEN-LAST:event_RLibroMouseExited

    private void RestudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestudiantesMouseExited
   if(CheckEstudiantes == false){
    Restudiantes.setBackground(new Color(255,255,255));
      }
     else if(CheckEstudiantes == true){
    // estudiantes
     }
    // TODO add your handling code here:
    }//GEN-LAST:event_RestudiantesMouseExited

    private void RPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPrestamosMouseExited
     if(CheckPrestamo == false){
    RPrestamos.setBackground(new Color(255,255,255));
      }
     else if(CheckPrestamo == true){
    // prestamo
     }
    }//GEN-LAST:event_RPrestamosMouseExited

    private void RLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RLibroMouseClicked
      if(CheckLibro == false){
          RLibro.setBackground(new Color(0,255,0,60));
          lblRLibro.setText("<html><h3>Libros (✓)</html></h3>");
          CheckLibro=true;
          
      }
     else if(CheckLibro == true){
         RLibro.setBackground(new Color(255,255,255));
          lblRLibro.setText("<html><h3>Libros</html></h3>");
          CheckLibro=false;
      }
    }//GEN-LAST:event_RLibroMouseClicked

    private void RestudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestudiantesMouseClicked
      if(CheckEstudiantes == false){
          Restudiantes.setBackground(new Color(0,255,0,60));
          lblREstudiantes.setText("<html><h3>Estudiantes (✓)</html></h3>");
          CheckEstudiantes=true;
          
      }
     else if(CheckEstudiantes == true){
         Restudiantes.setBackground(new Color(255,255,255));
          lblREstudiantes.setText("<html><h3>Estudiantes</html></h3>");
          CheckEstudiantes=false;
      }     
        
        
    }//GEN-LAST:event_RestudiantesMouseClicked

    private void RPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPrestamosMouseClicked
     if(CheckPrestamo == false){
          RPrestamos.setBackground(new Color(0,255,0,60));
          lblRPrestamos.setText("<html><h3>Prestamos (✓)</html></h3>");
          CheckPrestamo=true;
          
      }
     else if(CheckPrestamo == true){
         RPrestamos.setBackground(new Color(255,255,255));
          lblRPrestamos.setText("<html><h3>Prestamos</html></h3>");
          CheckPrestamo=false;
      }
    }//GEN-LAST:event_RPrestamosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void btn_generarreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarreportesActionPerformed
    //Agh
    //boolean firstuse= true;
    //if(firstuse==true){
        JOptionPane.showMessageDialog(null, "Selecciona solo la carpeta en donde se guardara el reporte");
        //firstuse= true;
    //}else if(firstuse==false){
   //}
    //Radver.setVisible(true);
    
    try{
    JFileChooser ch = new JFileChooser();
    ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int se = ch.showSaveDialog(null);
      
    if(se == JFileChooser.APPROVE_OPTION){
    String ruta = ch.getSelectedFile().getPath();
   // String ruta = ch.getSelectedFile().getAbsolutePath()+".xlsx";
    Logic.Metodos_Reporte mr = new Logic.Metodos_Reporte();
    
    /////1
    if(CheckLibro==false  && CheckEstudiantes==false && CheckPrestamo==false && CheckPersonal==false){
        JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun reporte");
    }
    //////////////2//////////////
    if(CheckLibro==false  && CheckEstudiantes==false && CheckPrestamo==false && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    mr.reporte_personal(ruta);
    Rwait.dispose();
   
     //seratchlblsdready.setText("<html><h2>Reporte generado con exito</h2></html>");
     JOptionPane.showMessageDialog(null, "Reporte generado con exito");

    }
  });  
hiloaccion.start();
 }
     ///////////////3/////////////
    if(CheckLibro==false  && CheckEstudiantes==false && CheckPrestamo==true && CheckPersonal==false){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    mr.reporte_prestamos(ruta);
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reporte generado con exito");

    }
  });  
hiloaccion.start();
 }
     ///////////////////4/////////
    if(CheckLibro==false  && CheckEstudiantes==false && CheckPrestamo==true && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/2)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/2)...</h2></html>");
    mr.reporte_prestamos(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/2)...</h2></html>");
    mr.reporte_personal(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
        ///////////////////5/////////
    if(CheckLibro==false  && CheckEstudiantes==true && CheckPrestamo==false && CheckPersonal==false){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    mr.reporte_estudiantes(ruta);
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reporte generado con exito");

    }
  });  
hiloaccion.start();
 }
        ///////////////////6/////////
    if(CheckLibro==false  && CheckEstudiantes==true && CheckPrestamo==false && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/2)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/2)...</h2></html>");
    mr.reporte_estudiantes(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/2)...</h2></html>");
    mr.reporte_personal(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
     ///////////////////7/////////
    if(CheckLibro==false  && CheckEstudiantes==true && CheckPrestamo==true && CheckPersonal==false){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/2)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/2)...</h2></html>");
    mr.reporte_estudiantes(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/2)...</h2></html>");
    mr.reporte_prestamos(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
    ///////////////////8/////////
    if(CheckLibro==false  && CheckEstudiantes==true && CheckPrestamo==true && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/3)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/3)...</h2></html>");
    mr.reporte_estudiantes(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/3)...</h2></html>");
    mr.reporte_prestamos(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (3/3)...</h2></html>");
    mr.reporte_personal(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
       ///////////////////9/////////
    if(CheckLibro==true  && CheckEstudiantes==false && CheckPrestamo==false && CheckPersonal==false){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
       Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    mr.reporte_estudiantes(ruta);
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reporte generado con exito");

    }
  });  
hiloaccion.start();
 }
        ////////////////////////////10
    if(CheckLibro==true  && CheckEstudiantes==false && CheckPrestamo==false && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/2)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/2)...</h2></html>");
    mr.reporte_libros(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/2)...</h2></html>");
    mr.reporte_personal(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
           ////////////////////////////11
    if(CheckLibro==true  && CheckEstudiantes==false && CheckPrestamo==true && CheckPersonal==false){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/2)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/2)...</h2></html>");
    mr.reporte_libros(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/2)...</h2></html>");
    mr.reporte_prestamos(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
              ////////////////////////////12
    if(CheckLibro==true  && CheckEstudiantes==false && CheckPrestamo==true && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/3)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/3)...</h2></html>");
    mr.reporte_libros(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/3)...</h2></html>");
    mr.reporte_prestamos(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (3/3)...</h2></html>");
    mr.reporte_personal(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
                 ////////////////////////////1/3
    if(CheckLibro==true  && CheckEstudiantes==true && CheckPrestamo==false && CheckPersonal==false){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/2)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/2)...</h2></html>");
    mr.reporte_libros(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/2)...</h2></html>");
    mr.reporte_estudiantes(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
                  ////////////////////////////14
    if(CheckLibro==true  && CheckEstudiantes==true && CheckPrestamo==false && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/3)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/3)...</h2></html>");
    mr.reporte_libros(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/3)...</h2></html>");
    mr.reporte_estudiantes(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (3/3)...</h2></html>");
    mr.reporte_personal(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
       ////////////////////////////15
    if(CheckLibro==true  && CheckEstudiantes==true && CheckPrestamo==true && CheckPersonal==false){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/3)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    
    lblwaitr.setText("<html><h2>Generando reportes (1/3)...</h2></html>");
    mr.reporte_libros(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/3)...</h2></html>");
    mr.reporte_estudiantes(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (3/3)...</h2></html>");
    mr.reporte_prestamos(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }
    ////////////////////////////////////////////////////////////////////////
    if(CheckLibro==true  && CheckEstudiantes==true && CheckPrestamo==true && CheckPersonal==true){
    Thread hiloespera = new Thread(new Runnable() {
    @Override
    public void run() {
        lblwaitr.setText("<html><h2>Generando reportes (0/4)...</h2></html>");
        Rwait.setVisible(true);
    }
    });  
    hiloespera.start();
    
    Thread hiloaccion = new Thread(new Runnable() {
    @Override
    public void run() {
    lblwaitr.setText("<html><h2>Generando reportes (1/4)...</h2></html>");
    mr.reporte_libros(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (2/4)...</h2></html>");
    mr.reporte_estudiantes(ruta);
    
    
    lblwaitr.setText("<html><h2>Generando reportes (3/4)...</h2></html>");
    mr.reporte_prestamos(ruta);
    
    lblwaitr.setText("<html><h2>Generando reportes (4/4)...</h2></html>");
    mr.reporte_personal(ruta);
    
    Rwait.dispose();
    JOptionPane.showMessageDialog(null, "Reportes generados con exito");

    }
  });  
hiloaccion.start();
 }     
      
      
      
      
      
      
      
      
    
     }
    
    
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Ocurrio un problema en la generacion del reporte "+e.getMessage());
        
    }
    }//GEN-LAST:event_btn_generarreportesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Rready.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Radver.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPersonalMouseEntered
        if(CheckPersonal == false){
            RPersonal.setBackground(new Color(241,241,241));
        }
        else if(CheckPersonal == true){

        }

    }//GEN-LAST:event_RPersonalMouseEntered

    private void RPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPersonalMouseExited
        if(CheckPersonal == false){
            RPersonal.setBackground(new Color(255,255,255));
        }
        else if(CheckPersonal == true){
            // personal
        }
    }//GEN-LAST:event_RPersonalMouseExited

    private void RPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RPersonalMouseClicked
        if(CheckPersonal == false){
            RPersonal.setBackground(new Color(0,255,0,60));
            lblRPersonal.setText("<html><h3>Personal (✓)</html></h3>");
            CheckPersonal=true;

        }
        else if(CheckPersonal == true){
            RPersonal.setBackground(new Color(255,255,255));
            lblRPersonal.setText("<html><h3>Personal</html></h3>");
            CheckPersonal=false;
        }
    }//GEN-LAST:event_RPersonalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Center_encabezado;
    private javax.swing.JPanel Optionreport;
    private javax.swing.JPanel Panel_BotonesRep;
    private javax.swing.JPanel Panel_centroreportes;
    private javax.swing.JPanel RLibro;
    private javax.swing.JPanel RPersonal;
    private javax.swing.JPanel RPrestamos;
    public static javax.swing.JDialog Radver;
    private javax.swing.JPanel Restudiantes;
    public static javax.swing.JDialog Rready;
    public static javax.swing.JDialog Rwait;
    private javax.swing.JButton btn_generarreportes;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblREstudiantes;
    private javax.swing.JLabel lblRLibro;
    private javax.swing.JLabel lblRPersonal;
    private javax.swing.JLabel lblRPrestamos;
    private javax.swing.JLabel lbl_cerrar;
    private javax.swing.JLabel lbl_encabezado_qr;
    public static javax.swing.JLabel lblready;
    public static javax.swing.JLabel lblwaitr;
    public static javax.swing.JLabel lblwaitr1;
    private javax.swing.JPanel panel_button;
    private javax.swing.JPanel paneladver;
    // End of variables declaration//GEN-END:variables

  
}
